version: "3.8"

services:
  db:
    image: postgres:15-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: jobq
      POSTGRES_PASSWORD: jobq
      POSTGRES_DB: jobq
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=en-US-u-kn-true"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
