version: "3.8"

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:15-bullseye
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=en-US-u-kn-true"
      POSTGRES_USER: jobq
      POSTGRES_PASSWORD: jobq
      POSTGRES_DB: jobq
    ports:
      - 35432:5432

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      NO_PROXY: "172.0.0.0/8"
      no_proxy: "172.0.0.0/8"
      http_proxy: ""
      https_proxy: ""
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14250:14250"
      - "14268:14268"
      - "16686:16686"
     

